# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3224398620b6ad43b6bf9b9c267908b7"
name = "xtal-search"
handle = "xtal-search"
application_url = "https://network-disclaimer-exist-its.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-dc84e1d9.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://mario-addition-lottery-fireplace.trycloudflare.com/auth/callback",
  "https://mario-addition-lottery-fireplace.trycloudflare.com/auth/shopify/callback",
  "https://mario-addition-lottery-fireplace.trycloudflare.com/api/auth/callback",
  "https://collectible-ranger-zip-written.trycloudflare.com/auth/callback",
  "https://collectible-ranger-zip-written.trycloudflare.com/auth/shopify/callback",
  "https://collectible-ranger-zip-written.trycloudflare.com/api/auth/callback",
  "https://victoria-observations-footwear-budapest.trycloudflare.com/auth/callback",
  "https://victoria-observations-footwear-budapest.trycloudflare.com/auth/shopify/callback",
  "https://victoria-observations-footwear-budapest.trycloudflare.com/api/auth/callback",
  "https://humanities-loading-return-bottle.trycloudflare.com/auth/callback",
  "https://humanities-loading-return-bottle.trycloudflare.com/auth/shopify/callback",
  "https://humanities-loading-return-bottle.trycloudflare.com/api/auth/callback",
  "https://presents-trends-penalty-bibliographic.trycloudflare.com/auth/callback",
  "https://presents-trends-penalty-bibliographic.trycloudflare.com/auth/shopify/callback",
  "https://presents-trends-penalty-bibliographic.trycloudflare.com/api/auth/callback",
  "https://welsh-routing-vertex-icon.trycloudflare.com/auth/callback",
  "https://welsh-routing-vertex-icon.trycloudflare.com/auth/shopify/callback",
  "https://welsh-routing-vertex-icon.trycloudflare.com/api/auth/callback",
  "https://marble-employ-updates-movie.trycloudflare.com/auth/callback",
  "https://marble-employ-updates-movie.trycloudflare.com/auth/shopify/callback",
  "https://marble-employ-updates-movie.trycloudflare.com/api/auth/callback",
  "https://recording-pollution-oral-karl.trycloudflare.com/auth/callback",
  "https://recording-pollution-oral-karl.trycloudflare.com/auth/shopify/callback",
  "https://recording-pollution-oral-karl.trycloudflare.com/api/auth/callback",
  "https://children-mail-occupations-modified.trycloudflare.com/auth/callback",
  "https://children-mail-occupations-modified.trycloudflare.com/auth/shopify/callback",
  "https://children-mail-occupations-modified.trycloudflare.com/api/auth/callback",
  "https://bone-sorry-suppose-choices.trycloudflare.com/auth/callback",
  "https://bone-sorry-suppose-choices.trycloudflare.com/auth/shopify/callback",
  "https://bone-sorry-suppose-choices.trycloudflare.com/api/auth/callback",
  "https://network-disclaimer-exist-its.trycloudflare.com/auth/callback",
  "https://network-disclaimer-exist-its.trycloudflare.com/auth/shopify/callback",
  "https://network-disclaimer-exist-its.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
