# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3224398620b6ad43b6bf9b9c267908b7"
name = "xtal-search"
handle = "xtal-search"
application_url = "https://foul-patients-optional-humanity.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-dc84e1d9.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://foul-patients-optional-humanity.trycloudflare.com/auth/callback",
  "https://foul-patients-optional-humanity.trycloudflare.com/auth/shopify/callback",
  "https://foul-patients-optional-humanity.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
