# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3224398620b6ad43b6bf9b9c267908b7"
name = "xtal-search"
handle = "xtal-search"
application_url = "https://preserve-maintenance-nathan-fraction.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-dc84e1d9.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://mario-addition-lottery-fireplace.trycloudflare.com/auth/callback",
  "https://mario-addition-lottery-fireplace.trycloudflare.com/auth/shopify/callback",
  "https://mario-addition-lottery-fireplace.trycloudflare.com/api/auth/callback",
  "https://needed-element-martha-diversity.trycloudflare.com/auth/callback",
  "https://needed-element-martha-diversity.trycloudflare.com/auth/shopify/callback",
  "https://needed-element-martha-diversity.trycloudflare.com/api/auth/callback",
  "https://u-noon-employee-eyes.trycloudflare.com/auth/callback",
  "https://u-noon-employee-eyes.trycloudflare.com/auth/shopify/callback",
  "https://u-noon-employee-eyes.trycloudflare.com/api/auth/callback",
  "https://organizations-visited-def-paint.trycloudflare.com/auth/callback",
  "https://organizations-visited-def-paint.trycloudflare.com/auth/shopify/callback",
  "https://organizations-visited-def-paint.trycloudflare.com/api/auth/callback",
  "https://preserve-maintenance-nathan-fraction.trycloudflare.com/auth/callback",
  "https://preserve-maintenance-nathan-fraction.trycloudflare.com/auth/shopify/callback",
  "https://preserve-maintenance-nathan-fraction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
